stages:
- name: Build and static unit
  steps:
  - runScriptConfig:
      image: maven:3-jdk-7
      shellScript: |
        mkdir -p /root/.m2 && mv settings.xml /root/.m2/
        mvn clean install org.sonarsource.scanner.maven:sonar-maven-plugin:3.5.0.1254:sonar \
          -Dsonar.host.url=${SONAR_HOST} \
          -Dsonar.login=${SONAR_KEY}
    env:
      NEXUS_HOST: http://sonatype-nexus-service.sonatype-nexus-hhtq2:8081
    envFrom:
    - sourceName: nexus-key
      sourceKey: token
      targetKey: NEXUS_TOKEN
    - sourceName: sonar-key
      sourceKey: host
      targetKey: SONAR_HOST
    - sourceName: sonar-key
      sourceKey: token
      targetKey: SONAR_KEY
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example-greenhouse:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: registry.gitlab.com/qiang1981cn/pipeline-example-maven
- name: Deploy
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:pipeline-chart-demo
      version: 0.1.0
      name: chart-training
      targetNamespace: chart-deploy
notification: {}
